import type { Metadata, Viewport } from 'next'
import { Providers } from '@/app/providers'
import { APP_NAME } from '@/lib/constants'
import '@/index.css'

export const metadata: Metadata = {
  title: APP_NAME,
  description: 'Travel planning for long-distance couples.',
  // Next reads this to emit the manifest link. The manifest itself is
  // generated by src/app/manifest.ts.
  manifest: '/manifest.webmanifest',
  applicationName: APP_NAME,
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
    apple: [{ url: '/icons/apple-touch-icon.png', sizes: '180x180' }],
  },
  appleWebApp: {
    // iOS has no manifest support worth relying on: `display: standalone` is
    // read from this instead, and without it an installed icon opens Safari
    // chrome and all.
    capable: true,
    title: APP_NAME,
    // `default`, deliberately, not `black-translucent`. Translucent hands the
    // whole screen to the page including the strip under the clock, and every
    // sticky header then needs its own `env(safe-area-inset-top)` or it renders
    // beneath the time and the battery. `default` has iOS reserve that space,
    // which is the same result with nothing to get wrong. The bottom inset
    // still applies either way, and AppShell handles it.
    statusBarStyle: 'default',
  },
  other: {
    // Next emits only the standardised `mobile-web-app-capable`, which Chrome
    // now prefers and which Apple did not originally implement. Older iOS
    // reads the `apple-` prefixed spelling and nothing else, and an iPhone that
    // does not see it opens the installed icon in a Safari window with the
    // address bar still there. Both are emitted; browsers ignore the one they
    // do not know.
    'apple-mobile-web-app-capable': 'yes',
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  themeColor: '#0b0d12',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
